name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://blog.davidmoll.net/feed.xml
          readme-section: feed
          template: <tr><td>{{ title }}</td><td>{{ link }}</td></tr>